#region LICENSE
// The contents of this file are subject to the Common Public Attribution
// License Version 1.0. (the "License"); you may not use this file except in
// compliance with the License. You may obtain a copy of the License at
// https://github.com/NiclasOlofsson/MiNET/blob/master/LICENSE.
// The License is based on the Mozilla Public License Version 1.1, but Sections 14
// and 15 have been added to cover use of software over a computer network and
// provide for limited attribution for the Original Developer. In addition, Exhibit A has
// been modified to be consistent with Exhibit B.
// 
// Software distributed under the License is distributed on an "AS IS" basis,
// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
// the specific language governing rights and limitations under the License.
// 
// The Original Code is MiNET.
// 
// The Original Developer is the Initial Developer.  The Initial Developer of
// the Original Code is Niclas Olofsson.
// 
// All portions of the code written by Niclas Olofsson are Copyright (c) 2014-2025 Niclas Olofsson.
// All Rights Reserved.
#endregion

namespace MiNET.Net.EnumerationsTable;

public enum ActorType
{
    Undefined = 1,
    Chicken = 10,
    Cow = 11,
    Pig = 12,
    Sheep = 13,
    Wolf = 14,
    Villager = 15,
    MushroomCow = 16,
    Squid = 17,
    Rabbit = 18,
    Bat = 19,
    IronGolem = 20,
    SnowGolem = 21,
    Ocelot = 22,
    Horse = 23,
    Donkey = 24,
    Mule = 25,
    SkeletonHorse = 26,
    ZombieHorse = 27,
    PolarBear = 28,
    Llama = 29,
    Parrot = 30,
    Dolphin = 31,
    Zombie = 32,
    Creeper = 33,
    Skeleton = 34,
    Spider = 35,
    PigZombie = 36,
    Slime = 37,
    EnderMan = 38,
    Silverfish = 39,
    CaveSpider = 40,
    Ghast = 41,
    LavaSlime = 42,
    Blaze = 43,
    ZombieVillager = 44,
    Witch = 45,
    Stray = 46,
    Husk = 47,
    WitherSkeleton = 48,
    Guardian = 49,
    ElderGuardian = 50,
    Npc = 51,
    WitherBoss = 52,
    Dragon = 53,
    Shulker = 54,
    Endermite = 55,
    Agent = 56,
    Vindicator = 57,
    Phantom = 58,
    IllagerBeast = 59,
    ArmorStand = 61,
    TripodCamera = 62,
    Player = 63,
    ItemEntity = 64,
    PrimedTnt = 65,
    FallingBlock = 66,
    MovingBlock = 67,
    ExperiencePotion = 68,
    Experience = 69,
    EyeOfEnder = 70,
    EnderCrystal = 71,
    FireworksRocket = 72,
    Trident = 73,
    Turtle = 74,
    Cat = 75,
    ShulkerBullet = 76,
    FishingHook = 77,
    Chalkboard = 78,
    DragonFireball = 79,
    Arrow = 80,
    Snowball = 81,
    ThrownEgg = 82,
    Painting = 83,
    MinecartRideable = 84,
    LargeFireball = 85,
    ThrownPotion = 86,
    Enderpearl = 87,
    LeashKnot = 88,
    WitherSkull = 89,
    BoatRideable = 90,
    WitherSkullDangerous = 91,
    LightningBolt = 93,
    SmallFireball = 94,
    AreaEffectCloud = 95,
    MinecartHopper = 96,
    MinecartTnt = 97,
    MinecartChest = 98,
    MinecartFurnace = 99,
    MinecartCommandBlock = 100,
    LingeringPotion = 101,
    LlamaSpit = 102,
    EvocationFang = 103,
    EvocationIllager = 104,
    Vex = 105,
    IceBomb = 106,
    Balloon = 107,
    Pufferfish = 108,
    Salmon = 109,
    Drowned = 110,
    TropicalFish = 111,
    Fish = 112,
    Panda = 113,
    Pillager = 114,
    VillagerV2 = 115,
    ZombieVillagerV2 = 116,
    Shield = 117,
    WanderingTrader = 118,
    Lectern = 119,
    ElderGuardianGhost = 120,
    Fox = 121,
    Bee = 122,
    Piglin = 123,
    Hoglin = 124,
    Strider = 125,
    Zoglin = 126,
    PiglinBrute = 127,
    Goat = 128,
    GlowSquid = 129,
    Axolotl = 130,
    Warden = 131,
    Frog = 132,
    Tadpole = 133,
    Allay = 134,
    ChestBoatRideable = 136,
    TraderLlama = 137,
    Camel = 138,
    Sniffer = 139,
    Breeze = 140,
    BreezeWindChargeProjectile = 141,
    Armadillo = 142,
    WindChargeProjectile = 143,
    Bogged = 144,
    OminousItemSpawner = 145,
    Creaking = 146
}